general:
  device: cuda # cpu/cuda
  additional_naming_info: "beam10" # optional, st

dataset:
  data_path: "../data/datasets/NIST/NIST_split_filip/denovo_data/valid_with_denovo_info.jsonl" # REQUIRED!
  dataset_name: NIST_denovo # rcx/ZINC/NIST/...    REQUIRED! (for naming)
  data_split: valid # train/test/valid/... REQUIRED! (for naming)

dataloader:
  batch_size: 1 # DONT CHANGE THAT! for now (the predictions get mixed or sth.. BS1 works ok.)
  num_workers: 3

tokenizer_path: "../tokenizer/bbpe_tokenizer/bart_bbpe_1M_tokenizer.model" # REQUIRED!

generation_args:
  "top_k": null
  "top_p": null
  "do_sample": False
  "num_beams": 10
  "temperature": null
  "penalty_alpha": null
  "num_return_sequences": 10
  "max_length": 200
  "decoder_input_token": "<nist>"
  "length_penalty": 1.0 # (use for beam search otherwise set to 0)

