general:
  additional_naming_info: "" # optional
  ranking_function: "sss"  # sss/hss/morgan_tanimoto
  num_candidates: 1          # num candidates to retrieve from db search 1/10/50

dataset:
  reference_data: "data/nist/train.jsonl" # REQUIRED!
  query_data: "data/nist/valid.jsonl" # REQUIRED!
  dataset_name: NIST # rcx/ZINC/NIST/...    REQUIRED! (for naming)
  data_split: valid # train/test/valid/... REQUIRED! (for naming)

filtering_args:  # if you don't specify these, default ones are used
  max_num_peaks: 300
  max_mz: 500
  max_mol_repr_len: 100
  mol_repr: "smiles"
