general:
  device: cuda # cpu/cuda
  additional_naming_info: "beam10" # optional, st

dataset:
  data_path: "data/mace/MACE_r05.jsonl" # REQUIRED!
  dataset_name: MACE # rcx/ZINC/NIST/...    REQUIRED! (for naming)
  data_split: all # train/test/valid/... REQUIRED! (for naming)

dataloader:
  batch_size: 1 # DONT CHANGE THAT! for now (the predictions get mixed or sth.. BS1 works ok.)
  num_workers: 1 # DONT CHANGE THAT! other than 1 mixes up the predictions, doesn't make the process faster

tokenizer_path: "tokenizer/tokenizer_mf10M.model" # REQUIRED!

generation_args:
  "top_k": null
  "top_p": null
  "do_sample": False
  "num_beams": 10                 # change this for beam search (make it match)
  "temperature": null
  "penalty_alpha": null
  "num_return_sequences": 10      # change this for beam search (make it match)
  "max_length": 200
  "decoder_input_token": "<nist>"
  "length_penalty": 1.0 # (use for beam search otherwise set to 0)

preprocess_args:
    "source_token": "<nist>"
    "restrict_intensities": False
    "inference_mode": True
    "keep_all_columns": True
    "max_num_peaks": 300
    "max_mol_repr_len": 100
    "max_mz": 500
    "mol_repr": "smiles"
    "log_base": 1.28
    "log_shift": 29
    "max_cumsum": null
